name: Windows RDP Server

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600
    outputs:
      tailscale_ip: ${{ steps.ts.outputs.tailscale_ip }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Core RDP Settings
        shell: pwsh
        run: .github/workflows/scripts/win-configure-rdp.ps1

      - name: Create RDP User with Secure Password
        shell: pwsh
        run: .github/workflows/scripts/win-create-user.ps1

      - name: Install Tailscale
        shell: pwsh
        run: .github/workflows/scripts/win-install-tailscale.ps1

      - name: Establish Tailscale Connection
        shell: pwsh
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        id: ts
        run: |
          .github/workflows/scripts/win-establish-ts.ps1
          if (-not $env:TAILSCALE_IP) { throw "TAILSCALE_IP missing" }
          "tailscale_ip=$env:TAILSCALE_IP" | Out-File -FilePath "$env:GITHUB_OUTPUT" -Append -Encoding utf8

      - name: Publish Tailscale IP artifact
        if: ${{ steps.ts.outputs.tailscale_ip != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: ts-ip
          path: ts-ip.txt
        shell: pwsh
        run: |
          Set-Content -Path ts-ip.txt -Value $env:TAILSCALE_IP -Encoding UTF8

      - name: Verify RDP Accessibility
        shell: pwsh
        run: .github/workflows/scripts/win-verify-rdp.ps1

      - name: Maintain Connection
        shell: pwsh
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: vum"
          Write-Host "Password: <blank> (无需密码)"
          Write-Host "==================`n"
          while ($true) {
            Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
            Start-Sleep -Seconds 300
          }